### ISSUE TITLE
Test target fails

### ISSUE THREAD

**Issue by NGoetz** [smash-transport/smash-vhlle-hybrid#29]
I get following error during execution of the test target:

``` 
File "/lustre/hyihp/ngoetz/smash-vhlle-hybrid/python_scripts/create_vhlle_config.py", line 37, in <module>
  File "/lustre/hyihp/ngoetz/smash-vhlle-hybrid/python_scripts/create_vhlle_config.py", line 37, in <module>
Traceback (most recent call last):
  File "/lustre/hyihp/ngoetz/smash-vhlle-hybrid/python_scripts/create_vhlle_config.py", line 37, in <module>
Traceback (most recent call last):
  File "/lustre/hyihp/ngoetz/smash-vhlle-hybrid/python_scripts/create_vhlle_config.py", line 37, in <module>
    if float(args.energy) >= float(key): energy = key
    if float(args.energy) >= float(key): energy = key
TypeError: float() argument must be a string or a real number, not 'NoneType'
TypeError: float() argument must be a string or a real number, not 'NoneType'
    if float(args.energy) >= float(key): energy = key
TypeError: float() argument must be a string or a real number, not 'NoneType'
    if float(args.energy) >= float(key): energy = key
TypeError: float() argument must be a string or a real number, not 'NoneType'
make[3]: *** [CMakeFiles/test_hydro.dir/build.make:107: Hybrid_Results/test/3/Hydro/vhlle_config] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: *** [CMakeFiles/test_hydro.dir/build.make:112: Hybrid_Results/test/4/Hydro/vhlle_config] Error 1
make[3]: *** [CMakeFiles/test_hydro.dir/build.make:102: Hybrid_Results/test/2/Hydro/vhlle_config] Error 1
make[3]: *** [CMakeFiles/test_hydro.dir/build.make:97: Hybrid_Results/test/1/Hydro/vhlle_config] Error 1
make[2]: *** [CMakeFiles/Makefile2:5135: CMakeFiles/test_hydro.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:5142: CMakeFiles/test_hydro.dir/rule] Error 2
make: *** [Makefile:2464: test_hydro] Error 2
```

**Comment by NGoetz** [comment]
I think this is probably because of the change in the config format.

**Comment by NGoetz** [comment]
This is solved by the new version.
